name = "presentation-feedback"
compatibility_date = "2024-01-01"

# Main entry point for Pages Functions
pages_build_output_dir = "out"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "presentation-feedback"
database_id = "d3f4ff4a-593b-4656-933f-e9933b37f9fb"
